poaonrails/config/routes.rb
Rails.application.routes.draw do
  resources :statistics
  resources :badges
  resources :features
  resources :ratings
  resources :users
  resources :schools
  get '/api/poaonrails/schools/:name', to: 'schools#list', as: 'schools_list'
  get '/api/poaonrails/ratings/:school_id', to: 'ratings#list', as: 'ratings_list_by_school'
  post '/api/poaonrails/ratings/create/new', to: 'ratings#register', as: 'create_rating'
  post '/api/poaonrails/users/create/new', to: 'users#register', as: 'create_user'
  post '/api/poaonrails/users/login', to: 'users#login', as: 'login_user'
  get '/api/poaonrails/features/:school_id', to: 'features#list', as: 'feature_list'
  get '/api/poaonrails/badges/:school_id', to: 'badges#list', as: 'badge_list'
  get '/api/poaonrails/school/:school_id', to: 'schools#find', as: 'find_school_by_id'

end

poaonrails/app/models/statistic.rb
class Statistic < ActiveRecord::Base
  belongs_to :school
end

poaonrails/app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:danger_district, :ratings, :security, :accessibility, :teaching, :infrastruc, :school_id)
    end
end

poaonrails/app/helpers/statistics_helper.rb
module StatisticsHelper
end

poaonrails/app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :danger_district %><br>
    <%= f.text_field :danger_district %>
  </div>
  <div class="field">
    <%= f.label :ratings %><br>
    <%= f.text_field :ratings %>
  </div>
  <div class="field">
    <%= f.label :security %><br>
    <%= f.text_field :security %>
  </div>
  <div class="field">
    <%= f.label :accessibility %><br>
    <%= f.text_field :accessibility %>
  </div>
  <div class="field">
    <%= f.label :teaching %><br>
    <%= f.text_field :teaching %>
  </div>
  <div class="field">
    <%= f.label :infrastruc %><br>
    <%= f.text_field :infrastruc %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.text_field :school_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

poaonrails/app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

poaonrails/app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statistics</h1>

<table>
  <thead>
    <tr>
      <th>Danger district</th>
      <th>Ratings</th>
      <th>Security</th>
      <th>Accessibility</th>
      <th>Teaching</th>
      <th>Infrastruc</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.danger_district %></td>
        <td><%= statistic.ratings %></td>
        <td><%= statistic.security %></td>
        <td><%= statistic.accessibility %></td>
        <td><%= statistic.teaching %></td>
        <td><%= statistic.infrastruc %></td>
        <td><%= statistic.school %></td>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_statistic_path %>

poaonrails/app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

poaonrails/app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Danger district:</strong>
  <%= @statistic.danger_district %>
</p>

<p>
  <strong>Ratings:</strong>
  <%= @statistic.ratings %>
</p>

<p>
  <strong>Security:</strong>
  <%= @statistic.security %>
</p>

<p>
  <strong>Accessibility:</strong>
  <%= @statistic.accessibility %>
</p>

<p>
  <strong>Teaching:</strong>
  <%= @statistic.teaching %>
</p>

<p>
  <strong>Infrastruc:</strong>
  <%= @statistic.infrastruc %>
</p>

<p>
  <strong>School:</strong>
  <%= @statistic.school %>
</p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>