poaonrails/config/routes.rb
Rails.application.routes.draw do
  resources :statistics
  resources :badges
  resources :features
  resources :ratings
  resources :users
  resources :schools
  get '/api/poaonrails/schools/:name', to: 'schools#list', as: 'schools_list'
  get '/api/poaonrails/ratings/:school_id', to: 'ratings#list', as: 'ratings_list_by_school'
  post '/api/poaonrails/ratings/create/new', to: 'ratings#register', as: 'create_rating'
  post '/api/poaonrails/users/create/new', to: 'users#register', as: 'create_user'
  post '/api/poaonrails/users/login', to: 'users#login', as: 'login_user'
  get '/api/poaonrails/features/:school_id', to: 'features#list', as: 'feature_list'
  get '/api/poaonrails/badges/:school_id', to: 'badges#list', as: 'badge_list'
  get '/api/poaonrails/school/:school_id', to: 'schools#find', as: 'find_school_by_id'

end

poaonrails/app/models/badge.rb
class Badge < ActiveRecord::Base
  belongs_to :school, :foreign_key => :cod
end

poaonrails/app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  def list
    code = params[:school_id]
    @badges = Badge.where(school_id: code)
    render :json => @badges
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description, :category, :icon, :school_id)
    end
end

poaonrails/app/helpers/badges_helper.rb
module BadgesHelper
end

poaonrails/app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.text_field :school_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

poaonrails/app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

poaonrails/app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Icon</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= badge.description %></td>
        <td><%= badge.category %></td>
        <td><%= badge.icon %></td>
        <td><%= badge.school %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

poaonrails/app/views/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

poaonrails/app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @badge.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @badge.category %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @badge.icon %>
</p>

<p>
  <strong>School:</strong>
  <%= @badge.school %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>