poaonrails/config/routes.rb
Rails.application.routes.draw do
  resources :statistics
  resources :badges
  resources :features
  resources :ratings
  resources :users
  resources :schools
  get '/api/poaonrails/schools/:name', to: 'schools#list', as: 'schools_list'
  get '/api/poaonrails/ratings/:school_id', to: 'ratings#list', as: 'ratings_list_by_school'
  post '/api/poaonrails/ratings/create/new', to: 'ratings#register', as: 'create_rating'
  post '/api/poaonrails/users/create/new', to: 'users#register', as: 'create_user'
  post '/api/poaonrails/users/login', to: 'users#login', as: 'login_user'
  get '/api/poaonrails/features/:school_id', to: 'features#list', as: 'feature_list'
  get '/api/poaonrails/badges/:school_id', to: 'badges#list', as: 'badge_list'
  get '/api/poaonrails/school/:school_id', to: 'schools#find', as: 'find_school_by_id'

end

poaonrails/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :school
end

poaonrails/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  def list
    school_id = params[:school_id]
    @school = School.find(school_id)
    @ratings = @school.ratings
    render :json => @ratings
  end

  def register
    rating_params = extract_rating_params()
    rating = Rating.create(rating_params)
    rating.save
    render :json => rating
  end

  def extract_rating_params
    user_id = params[:user_id]
    school_id = params[:school_id]
    pros = params[:pros]
    cons = params[:cons]
    rating = params[:rating]
    category = params[:category]
    return {user_id: user_id, school_id: school_id, pros: pros, cons: cons, rating: rating, category: category}
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:user_id, :school_id, :pros, :cons, :rating, :category)
    end
end

poaonrails/app/helpers/ratings_helper.rb
module RatingsHelper
end

poaonrails/app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.text_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :pros %><br>
    <%= f.text_area :pros %>
  </div>
  <div class="field">
    <%= f.label :cons %><br>
    <%= f.text_area :cons %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

poaonrails/app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

poaonrails/app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>School</th>
      <th>Pros</th>
      <th>Cons</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.user %></td>
        <td><%= rating.school %></td>
        <td><%= rating.pros %></td>
        <td><%= rating.cons %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.category %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

poaonrails/app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

poaonrails/app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>School:</strong>
  <%= @rating.school %>
</p>

<p>
  <strong>Pros:</strong>
  <%= @rating.pros %>
</p>

<p>
  <strong>Cons:</strong>
  <%= @rating.cons %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>